name: Frust work
on: workflow_dispatch
jobs:
  firt-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print geeedeng
        run: echo "Hello"
      - name: goodby
        run: echo "Bay done"
        
