name: First workflow
on: [workflow_dispatch, push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Runnig first job
        run: echo "hi shell"
      - name: check os relies
        run: cat /etc/os-release
      - name: good bay
        run: echo "Bay done"
      - name: not bay
        run: |
          echo "bay none"
          sleep 15
  next-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: checking host name
        run: hostname
      - name: run mutiple comands
        run: |
          echo "hi 1"
          echo "hi 2 'date'"   
          sleep 10
  next-job-3:
    name: job3
    needs: [first-job, next-job] 
    runs-on: ubuntu-latest
    steps:
      - name: checking host name
        run: hostname
      - name: run mutiple comands
        run: |
          echo "hi 1"
          echo "hi 2 'date'"   
          sleep 10

  next-job-4:
    name: job3
    needs: [first-job, next-job,next-job-3] 
    runs-on: ubuntu-latest
    steps:
      - name: checking host name
        run: hostname
      - name: run mutiple comands
        run: |
          echo "hi 1"
          echo "hi 2 'date'"   
          sleep 10
