name: First workflow
on: [workflow_dispatch, push]
jobs:
  firt-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print geeedeng
        run: echo "Hello"
      - name: good bay
        run: echo "Bay done"
      - name: not bay
        run: echo "bay none"
        
